config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations'}
  devise_scope :user do
    authenticated :user do
      root "categories#index", as: :authenticated_root
    end
    unauthenticated do
      root 'users/splash/', as: :unauthenticated_root, action: :new_splash, controller: 'categories'
    end
  end
  
  resources :categories
  resources :operations, only: [:index, :new, :create, :show]
  
  get 'categories/:category_id/operations/new_two', as: 'new_transaction', action: :new_two, controller: :operations
  post 'categories/:category_id/operations', as: 'create_transaction', action: :create_two, controller: :operations
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :manage, Operation, author_id: user.id
      can :manage, Category, user_id: user.id
      can :manage, Categorization, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :operation
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User'

  has_many :categorizations, dependent: :destroy
  has_many :operations, through: :categorizations, dependent: :destroy

  has_one_attached :icon, dependent: :destroy
  # validates_presence_of :icon
  validate :acceptable_icon

  validates :name, presence: true

  def acceptable_icon
    return unless icon.attached?

    errors.add(:icon, 'is too big') unless icon.byte_size <= 5.megabyte

    acceptable_types = ['image/jpeg', 'image/png']
    errors.add(:icon, 'must be a JPEG or PNG') unless acceptable_types.include?(icon.content_type)
  end

  def category_name
    name.to_s
  end

  def recent_transactions
    operations.order(created_at: :desc)
  end
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations, dependent: :destroy

  after_save :update_operations_counter

  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_decimal: true, greater_than: 0 }
  validates :categories, presence: true

  private

  def update_operations_counter
    @category = categories[0]
    @category.update_attribute(:operations_counter, @category.operations_counter += 1)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :operations, foreign_key: 'author_id', dependent: :destroy
  has_many :categories, dependent: :destroy

  validates :name, presence: true

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :null_session

  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to categories_url, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource

  skip_before_action :authenticate_user!, only: :new_splash
  before_action :set_category, only: :show

  def new_splash
    render 'devise/sessions/splash', layout: 'splash'
  end

  def index
    @page_title = 'Categories'
    @categories = current_user.categories.order(updated_at: :desc)
  end

  def show
    @page_title = 'Transactions'
    render layout: 'categories_show'
  end

  def new
    @page_title = 'Categories'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user
    respond_to do |format|
      if @category.save
        flash[:success] = 'Category has been created successfully'
        format.html { redirect_to categories_url }
      else
        flash[:danger] = 'Error: Category could not be created'
        format.html { redirect_to new_category_url }
      end
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end

  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  load_and_authorize_resource

  before_action :set_category, only: %i[new_two show create_two]

  def index
    @page_title = 'Transactions'
    @operations = current_user.operations
  end

  def show
    @page_title = 'Transactions'
    render layout: 'categories_show'
  end

  def new
    @page_title = 'Transactions'
    @operation = Operation.new
    @categorization = Categorization.new
  end

  def new_two
    @page_title = @category.name
    @operation = Operation.new
    @categorization = Categorization.new
  end

  def create
    @operation = Operation.new(operation_params)
    @categorization = Categorization.new
    @category_name = params[:categorization][:category]
    @operation.categories = [Category.find_by(name: @category_name)] unless @category_name.empty?
    @operation.author = current_user
    respond_to do |format|
      if @operation.save
        flash[:success] = 'Transaction has been created successfully'
        format.html { redirect_to operations_url }
      else
        flash[:danger] = 'Error: Transaction could not be created'
        format.html { redirect_to new_operation_path }
      end
    end
  end

  def create_two
    @operation = Operation.new(operation_params)
    @operation.author = current_user
    @operation.categories = [@category]
    respond_to do |format|
      if @operation.save
        flash[:success] = 'Transaction has been created successfully'
        format.html { redirect_to category_url(@category) }
      else
        flash[:danger] = 'Error: Transaction could not be created'
        format.html { redirect_to new_transaction_path(@category) }
      end
    end
  end

  private

  def operation_params
    params.require(:operation).permit(:name, :amount)
  end

  def set_category
    @category = Category.find(params[:category_id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  layout 'registrations'
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  layout 'sessions'
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_class?(test_path)
    return 'nav-link active' if request.path.include? test_path

    'nav-link'
  end

  def form_page?
    return true unless request.path.include? 'new'

    false
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def categories?
    out = ''
    if current_user.categories.empty?
      out << "<p class=\'align-self-center mt-5\'>This user has no categories registered</p>"
    end
    out.html_safe
  end
end

app/helpers/operations_helper.rb
module OperationsHelper
  def category_operations?(category)
    out = ''
    if category.operations.empty?
      out << "<p class=\'align-self-center mt-5\'>This category has no transactions registered</p>"
    end
    out.html_safe
  end

  def operations?
    out = ''
    if current_user.operations.empty?
      out << "<p class=\'align-self-center mt-5\'>This category has no transactions registered</p>"
    end
    out.html_safe
  end
end

app/views/categories/_category_card.html.erb
<%= link_to category_path(category), class:'text-decoration-none' do %>
  <li class='list-group-item m-2 border' id='<%= dom_id category %>'>
    <div class='category-card d-flex'>
      <div class='category-icon flex-1'>
          <%= image_tag(category.icon.url || 'https://picsum.photos/100', size: '75') %>
      </div>
      <div class='category-details positon-relative flex-fill ps-4 pt-2'>
        <p><%= category.name %></p>
        <p class='position-absolute bottom-0 text-muted'><%= category.updated_at.to_formatted_s(:long) %></p>
      </div>
      <div class='category-total flex-1'>
        <p>$<%= sprintf('%.2f', category.operations.sum(:amount)) %></p>
      </div>
    </div>
  </li>
<% end %>

app/views/categories/index.html.erb
<h2 class='text-center mt-2'>Categories List</h2>
<div class='categories-list'>
  <ul class='list-group d-flex flex-column'>
    <% @categories.each do |category| %>
      <%= render 'category_card', category: category %>
    <% end %>
    <%= categories? %>
  </ul>
</div>
<footer class="footer vw-100 py-3 bg-secondary fixed-bottom">
  <div class='d-flex justify-content-center'>
    <%= link_to 'Create category', new_category_path, class:'btn btn-outline-light w-75' %>
  </div>
</footer>

app/views/categories/new.html.erb
<%= form_with(model: @category, url: categories_path, method: :post, html: { class: 'category-form-new d-flex flex-column m-4' }, data: { turbo: false }) do |form| %>
  <% if @category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% @category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h3 class='mb-2 align-self-center'>New Category</h3>
  <div class="field mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "Enter a category name", class: 'form-control' %>
  </div>
  <div class="field mb-3">
    <%= form.label :icon %>
    <%= form.file_field :icon, class: 'form-control', required: true %>
  </div>
  <%= form.submit 'Save Category', class:"btn btn-primary"%>
<% end %>

app/views/categories/show.html.erb
<h4 class='text-center mt-2'>Transactions for <%= @category.name %></h4>
<br>
<h4 class='text-center'>Total: $<%= sprintf('%.2f', @category.operations.sum(:amount)) %></h4>
<div class='operations-list'>
  <ul class='list-group d-flex flex-column'>
    <% @category.recent_transactions.each do |operation| %>
      <%= render 'operations/operation_card', operation: operation %>
    <% end %>
    <%= category_operations?(@category) %>
  </ul>
</div>
<footer class="footer vw-100 py-3 bg-secondary fixed-bottom">
  <div class='d-flex justify-content-center'>
    <%= link_to 'Create transaction', new_transaction_path(@category), class:'btn btn-outline-light w-75' %>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <% if form_page? %>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <% else %>
          <%= link_to categories_path, class:'link-light' do %>
            <svg xmlns="http://www.w3.org/2000/svg" width="2.5em" fill="currentColor" class="bi bi-arrow-left-circle" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.5-.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
            </svg>
          <% end %>
        <% end %>
        <h4 class="m-0 d-lg-none <%= 'flex-fill text-center' unless form_page? %>"><%= @page_title %></h4>
        <h4 class="d-none d-lg-block m-0 <%= 'flex-fill text-center' unless form_page? %>">Budget App</h4>
        <% if form_page? %>
          <svg xmlns="http://www.w3.org/2000/svg" width="1.5em" fill="currentColor" class="bi bi-search d-lg-none" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
          </svg>
        <% end %>
        <% if form_page? %>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav container-fluid mb-2 mb-lg-0 ps-4">
              <li class="nav-item">
                <%= link_to "Categories", categories_path, :class => current_class?(categories_path) %>
              </li>
              <li class="nav-item">
                <%= link_to "Transactions", operations_path, :class => current_class?(operations_path) %>
              </li>
              <% if signed_in? %>
                <li class="nav-item ms-lg-auto">
                  <%= link_to "Edit User", edit_user_registration_path, class: 'nav-link ms-auto' %>              
                </li>
                <li class="nav-item d-flex align-items-center">
                  <%= button_to "Log Out", destroy_user_session_path, class: ' btn btn-outline-light px-1 py-0 ', method: :delete  %>              
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </nav>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: "alert alert-#{name}" %>
    <% end -%>
    <%= yield %>
  </body>
</html>

app/views/layouts/categories_show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <h4 class="m-0 d-lg-none <%= 'flex-fill text-center' unless form_page? %>"><%= @page_title %></h4>
        <h4 class="d-none d-lg-block m-0 <%= 'flex-fill text-center' unless form_page? %>">Budget App</h4>
        <% if form_page? %>
          <svg xmlns="http://www.w3.org/2000/svg" width="1.5em" fill="currentColor" class="bi bi-search d-lg-none" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
          </svg>
        <% end %>
        <% if form_page? %>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav container-fluid mb-2 mb-lg-0 ps-4">
              <li class="nav-item">
                <%= link_to "Categories", categories_path, :class => current_class?(categories_path) %>
              </li>
              <li class="nav-item">
                <%= link_to "Transactions", operations_path, :class => current_class?(operations_path) %>
              </li>
              <% if signed_in? %>
                <li class="nav-item ms-lg-auto">
                  <%= link_to "Edit User", edit_user_registration_path, class: 'nav-link ms-auto' %>              
                </li>
                <li class="nav-item d-flex align-items-center">
                  <%= button_to "Log Out", destroy_user_session_path, class: ' btn btn-outline-light px-1 py-0 ', method: :delete  %>              
                </li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </nav>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: "alert alert-#{name}" %>
    <% end -%>
    <%= yield %>
  </body>
</html>

app/views/layouts/registrations.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget - Register</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: "alert alert-#{name}" %>
    <% end -%>
    <%= yield %>
  </body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget - Log In</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/splash.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget - Splash</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/operations/_operation_card.html.erb
<li class='list-group-item m-2 border' id='<%= dom_id operation %>'>
  <div class='operation-card d-flex'>
    <div class='operation-details positon-relative flex-fill ps-4 pt-2'>
      <p><%= operation.name %></p>
      <p class='position-absolute bottom-0 text-muted'><%= operation.created_at.to_formatted_s(:long) %></p>
    </div>
    <div class='operation-total flex-1'>
      <p>$<%= sprintf('%.2f', operation.amount) %></p>
    </div>
  </div>
</li>

app/views/operations/index.html.erb
<h4 class='text-center mt-2'>All transactions from: <%= current_user.name %></h4>
<div class='operations-list'>
  <ul class='list-group d-flex flex-column'>
    <% @operations.each do |operation| %>
      <%= render 'operation_card', operation: operation %>
    <% end %>
    <%= operations? %>
  </ul>
</div>
<footer class="footer vw-100 py-3 bg-secondary fixed-bottom">
  <div class='d-flex justify-content-center'>
    <%= link_to 'Create transaction', new_operation_path, class:'btn btn-outline-light w-75' %>
  </div>
</footer>

app/views/operations/new.html.erb
<%= form_with(model: [@operation, @categorization], url: operations_path, method: :post, scope: @operation,
  html: { class: 'operation-form-new d-flex flex-column m-4' }, data: { turbo: false }) do |form| %>
  <% if @operation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if @categorization.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@categorization.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @categorization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h3 class='mb-2 align-self-center'>New transaction</h3>
  <div class="field mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "Enter a transaction name", class: 'form-control' %>
  </div>
  <div class="field mb-3">
    <%= form.label :amount %>
    <%= form.number_field :amount, step: '0.01', value: 0.0, class: 'form-control' %>
  </div>
  <div class="field mb-3">
    <%= form.label :category %>
    <%= collection_select(:categorization, :category, current_user.categories, :name, :category_name, prompt: true) %>
  </div>
  <%= form.submit 'Save Transaction', class:"btn btn-primary"%>
<% end %>

app/views/operations/new_two.html.erb
<%= form_with(model: @operation, url: create_transaction_path(@category), method: :post, scope: @operation,
  html: { class: 'operation-form-new d-flex flex-column m-4' }, data: { turbo: false }) do |form| %>
  <% if @operation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @operation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h3 class='mb-2 align-self-center'>New transaction for <%= @category.name %></h3>
  <div class="field mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder: "Enter a transaction name", class: 'form-control' %>
  </div>
  <div class="field mb-3">
    <%= form.label :amount %>
    <%= form.number_field :amount, step: '0.01', value: 0.0, class: 'form-control' %>
  </div>
  <%= form.submit 'Save Transaction', class:"btn btn-primary"%>
<% end %>